### ISSUE TITLE
fmod-gamermaker.dll file Does not exist?

### ISSUE THREAD

**Issue by JohnRabbitcoon** [femloy/OpenTower#23]
fmod-gamermaker.dll file Does not exist but when i check on the fmod_gms extension there is fmod-gamemaker.dll
like what. Why do i get this issue all the time? this has to be fixed.
Note: i got the fmod with all the music and sfx of pizza tower and it still doesnt work.
![image](https://github.com/user-attachments/assets/ba2cc775-a172-483d-9b53-0742511ce3e5)

**Comment by femloy** [comment]
fmod-gamemaker.dll is put in the datafiles folder after you finish the PTdecompiler.csx script
You can move it to the extension folder if you want it to be slightly more accurate

**Comment by JohnRabbitcoon** [comment]
theres only licenses. and in the licenses theres Gameframe thingy.
