### ISSUE TITLE
shd_pal_swapper issue

### ISSUE THREAD

**Issue by JohnRabbitcoon** [femloy/OpenTower#24]
i do not know why but its just broken after i fixed the fmod_gamemaker.dll
i do not know how that happened but shd_pal_swapper is broken as hell.

**Comment by JohnRabbitcoon** [comment]
update: i checked a random room with shd_pal_swapper and it said: number of arguments for function pal_swap_init_system expected 0 got 1

**Comment by femloy** [comment]
This is accurate. Please stop making issues
