### ISSUE TITLE
Steamworks broke it..

### ISSUE THREAD

**Issue by therealactualnoise** [femloy/OpenTower#28]
i got this error message when opening the settings [options]
 ############################################################################################
ERROR in
action number 1
of Create Event
for object obj_option:

Variable <unknown_object>.steam_utils_is_steam_running_on_steam_deck(103394, -2147483648) not set before reading it.
 at gml_Object_obj_option_Create_0 (line 127) - if !steam_utils_is_steam_running_on_steam_deck()
############################################################################################
gml_Object_obj_option_Create_0 (line 127)
gml_Script_instance_create (line 8)
gml_Object_obj_mainmenu_Step_0 (line 66) - 			with (instance_create(0, 0, obj_option))

**Comment by femloy** [comment]
Please read the README
