### ISSUE TITLE
Decompiler script failing on latest UTMT build.

### ISSUE THREAD

**Issue by spaghetto207** [femloy/OpenTower#31]
PTDecompiler.csx fails on the latest release of UTMT due to textureworker.cleanup() not being defined.

Steps:
Open latest UTMT -> Open latest steam release of PT
Run PTDecompiler.csx

Full Error Below:
`C:\Users\spaghetto\Documents\Github\OpenTower\PTdecompiler.csx(5350,8): error CS1061: 'TextureWorker' does not contain a definition for 'Cleanup' and no accessible extension method 'Cleanup' accepting a first argument of type 'TextureWorker' could be found (are you missing a using directive or an assembly reference?)`

this is probably a minor issue, just link to a specific UTMT build or fix the script itself.

**Comment by femloy** [comment]
Fixed but also I'd rather you not interact with me before having a little chat on Discord

**Comment by spaghetto207** [comment]
thats fine, i tried adding you but couldnt go through as you arent axcepting friends. if you want to add me instead its spagheto207
