### ISSUE TITLE
Gamemaker Not Starting up help

### ISSUE THREAD

**Issue by xander540** [femloy/OpenTower#33]
Everytime i try to open the gamemaker version im needing to use the Pizza Tower Decomp, GameMaker 2023.1.1.62 will not open. It will just stay in this screen forever. How do i fix this!?
![theissue](https://github.com/user-attachments/assets/8b2ca084-fa67-48af-b363-a92ebaecb206)

**Comment by internettyspaghetti** [comment]
i had the same issue
you can use the gamemaker version right after the required version, it runs fine ignoring the music being buggy  (ex. it stopping when restarting or exiting levels)

**Comment by femloy** [comment]
Clear your GameMaker cache at %programdata%.
