### ISSUE TITLE
achievement_boss lang value does not exist

### ISSUE THREAD

**Issue by objShaggy** [femloy/OpenTower#38]
The game looks for the language value achievement_boss for any of the boss achievements even tho this language value does not exist on any language text file.
![Screenshot 2024-10-26 232139](https://github.com/user-attachments/assets/d585b227-4898-4c04-9feb-cab58b8e06a8)

**Comment by femloy** [comment]
This is an issue with you not having updated Pizza Tower or using a mod prior to updating
