### ISSUE TITLE
Lockit HQ credits not working properly

### ISSUE THREAD

**Issue by objShaggy** [femloy/OpenTower#39]
The game looks for the lang value credits_lockit1 which doesn't exist, resulting for a long time on the credits screen where no text pops up.
![Screenshot 2024-10-26 233715](https://github.com/user-attachments/assets/26af9632-2f2c-4398-9bfa-0d7ffc7aef2a)

**Comment by femloy** [comment]
This is an issue with you not having updated Pizza Tower or using a mod prior to updating
