### ISSUE TITLE
old movement quirk, "block bug", is still present despite being patched in the base game

### ISSUE THREAD

**Issue by cocoasprinkle** [femloy/OpenTower#46]
block bug was a bug present in older versions of pizza tower that caused player vertical momentum to be zero'd when performing a power bomb through a breakable block. when playtesting for an online mod that i had made using opentower, one of my friends found out that this bug, despite being fixed months ago, had reappeared. since i haven't changed anything about the movement code i'll assume this is an opentower-specific bug
![ezgif-5-5d8c4738ce](https://github.com/user-attachments/assets/e14fa80b-9d0b-488c-a0db-9e6b42fcb625)

**Comment by femloy** [comment]
I genuinely have no idea why this happens and it's been pissing me off
Good to know someone else is having this issue too

**Comment by cocoasprinkle** [comment]
if it saves you any hassle i'll try to look into this myself by comparing the code differences in player scripts between a vanilla opentower build and a base game build, theres a good chance that they wouldve changed an argument or added a block somewhere in a way thats decently obvious to fix it

**Comment by femloy** [comment]
I've done exactly that, turns out scr_collide_player was missing an entire block
Oops.

**Comment by cocoasprinkle** [comment]
oh thank god lol, thanks loy

**Comment by cocoasprinkle** [comment]
uhhhhh loy? i dont think you ever actually updated scr_collide_player, so the bug is still present

**Comment by femloy** [comment]
scr_solid_player, line 28 through 33.

**Comment by cocoasprinkle** [comment]
oh whoops sorry, yea it seems to be alright now
