### ISSUE TITLE
Code not Porting over

### ISSUE THREAD

**Issue by Pizzabucket** [femloy/OpenTower#49]
When I port data.win to gms2 none of the code is ported. (1.0.5952)

**Comment by SillyBilly-123** [comment]
Could you specify what you mean by "porting"? Also, that version of Pizza Tower is very outdated, so many sprites will be missing

**Comment by Pizzabucket** [comment]
What I mean by “port” is running PTdecompiler. It extracts everything except the modded code.

**Comment by SillyBilly-123** [comment]
That's intended, it should only extract sprites and the necessary datafiles.
